[package]
name = "demo_rcv"
version = "0.1.0"
authors = ["Paul <paul@lancasterzone.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sacn = { path = "../../"}
error-chain = "0.12.2"
